apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prueba-tekton-anpen
  description: SVSM main website
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=svsm'
    backstage.io/kubernetes-namespace: svsm
    backstage.io/kubernetes-id: incibe-r01-svsm-app-x1
    janus-idp.io/tekton : incibe-r01-svsm-app-x1
  tags:
    - react
    - nodejs
  links:
    # - url: https://backstage-stg.aws.neoris.cloud/
    #   title: Web dev
    # icon: code
    - url: https://github.com/DDC-NEORIS/incibe-r01-svsm-app
      title: GitHub Repo
      icon: Github
    - url: https://github.com/DDC-NEORIS/incibe-r01-svsm-app-tests
      title: GitHub Testing X
      icon: Github
spec:
  type: demo
  lifecycle: production
  system: testops
  owner: neoris
